# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
branches:
  only:
  - develop
  - master
os: osx
osx_image: xcode11.4
language: swift
xcode_workspace: Example/SDStateTableView.xcworkspace # path to xcworkspace folder
xcode_scheme: SDStateTableView-Example
xcode_destination: platform=iOS Simulator,OS=9.3,name=iPhone 6s
podfile: Podfile
cache:
- bundler
- cocoapods
before_install:
- gem install bundler --pre
- gem install cocoapods
install:
- cd Example && pod install --repo-update && cd ..
jobs:
  include:
  - stage: build
    if: type = pull_request OR type = push
    script:
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SDStateTableView.xcworkspace -scheme SDStateTableView-Example -sdk iphonesimulator13.4 ONLY_ACTIVE_ARCH=NO | xcpretty
