# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
branches:
  only:
  - develop
  - master
os: osx
osx_image: xcode11.4
language: swift
xcode_workspace: Example/SDStateTableView.xcworkspace # path to xcworkspace folder
xcode_scheme: SDStateTableView-Example
xcode_destination: platform=iOS Simulator,OS=13.4.1,name=iPhone 8
podfile: Podfile
cache:
- bundler
- cocoapods
before_install:
- gem install bundler --pre
- gem install cocoapods
install:
- cd Example && pod install --repo-update && cd ..
jobs:
  include:
  - stage: build
    if: type = pull_request OR type = push
    script:
    - instruments -s devices
    - xcodebuild build test -workspace Example/SDStateTableView.xcworkspace -scheme  SDStateTableView-Example -destination 'platform=iOS Simulator,id=B442CB1C-FD52-48E6-BDC4-5BCE23210181' -enableCodeCoverage YES
after_success:
- bash <(curl -s https://codecov.io/bash)
